### ISSUE TITLE
Null Pointer Exception for occurrence on OBIS, but not on Biocache

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/obis-hub#5]
The following occurrence reliably generates a NullPointerException on OBIS, but does not do so on the current Biocache:

http://obis.ala.org.au/occurrences/deb81878-9f55-4c7b-b913-536ffa36f9ef

http://biocache.ala.org.au/occurrences/deb81878-9f55-4c7b-b913-536ffa36f9ef

The stack trace in the logs (as logging is not shown in the HTML page) is:

```
2016-10-27 02:03:50,166 ERROR [GrailsExceptionResolver]  NullPointerException occurred when processing request: [GET] /occurrences/deb81878-9f55-4c7b-b913-536ffa36f9ef
Cannot invoke method get() on null object. Stacktrace follows:
org.codehaus.groovy.grails.web.pages.exceptions.GroovyPagesException: Error processing GroovyPageView: Error executing tag <alatag:occurrenceTableRow>: Cannot invoke method get() on null object
    at grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:200)
    at grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
    at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
    at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
    at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:200)
    at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:110)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.groovy.grails.web.taglib.exceptions.GrailsTagException: Error executing tag <alatag:occurrenceTableRow>: Cannot invoke method get() on null object
    at gsp_biocacheHubs_occurrenceshow_gsp$_run_closure2.doCall(gsp_biocacheHubs_occurrenceshow_gsp.groovy:421)
    at gsp_biocacheHubs_occurrenceshow_gsp.run(gsp_biocacheHubs_occurrenceshow_gsp.groovy:831)
    ... 9 more
Caused by: java.lang.NullPointerException: Cannot invoke method get() on null object
    at gsp_biocacheHubs_occurrenceshow_gsp$_run_closure2_closure7.doCall(gsp_biocacheHubs_occurrenceshow_gsp.groovy:418)
    at au.org.ala.biocache.hubs.OccurrenceTagLib$_closure12.doCall(OccurrenceTagLib.groovy:444)
    ... 11 more
```

The current build info for obis.ala.org.au is:

```
Build Info
Build Date  Thu Oct 06 10:47:56 AEDT 2016
Source Control Revision Number  f6d9d25dfd09096f62727015f5961fa9ffe5530c
Runtime Application Status
Grails Environment  PRODUCTION
App version 0.2-SNAPSHOT
Grails version  2.3.11
JVM Version 1.7.0_80
Installed Plugins
alaAuth 1.3.4
alaBootstrap2   2.4.3-SNAPSHOT
biocacheHubs    1.2-SNAPSHOT
buildInfo   1.2.6
cache   1.1.1
cachedResources 1.0
cacheEhcache    1.0.0
cacheHeaders    1.1.6
codecs  2.3.11
controllers 2.3.11
converters  2.3.11
core    2.3.11
dataBinding 2.3.11
dataSource  2.3.11
domainClass 2.3.11
filters 2.3.11
fontAwesomeResources    4.3.0.1
groovyPages 2.3.11
i18n    2.3.11
imagesClientPlugin  0.7.5-SNAPSHOT
jquery  1.8.3
logging 2.3.11
mimeTypes   2.3.11
release 3.0.1
resources   1.2.8
rest    0.8
restClientBuilder   1.0.3
restResponder   2.3.11
services    2.3.11
servlets    2.3.11
urlMappings 2.3.11
validation  2.3.11
webxml  1.4.1
```

**Comment by ansell** [comment]
Seems like it could be related to duplicate records, as the following also fails, and are duplicate records according to biocache.ala.org.au (Is this a stealth mechanism for hiding duplicates?):

http://obis.ala.org.au/occurrences/f596f976-de4a-435b-ac8e-c437eff9aec4

**Comment by ansell** [comment]
May be related to the following code in biocache-hubs:

https://github.com/AtlasOfLivingAustralia/biocache-hubs/blob/master/grails-app/views/occurrence/show.gsp#L413

**Comment by ansell** [comment]
Initial attempt to fix failed https://github.com/AtlasOfLivingAustralia/biocache-hubs/commit/8f385da3746b78cc85329151df8421e81dc92f89 , but the line numbers (not the real line numbers due to grails compilation process) changed slightly, so may be in the right area.
